export const TarkeebPlaces = {
  ismInna: 'اسم إن',
  ismKaana: 'اسم كان',
  jaar: 'جارّ',
  haal: 'حال',
  khabr: 'خبر',
  khabrInna: 'خبر إن',
  khabrKaana: 'خبر كان',
  dhulHaal: 'ذو الحال',
  atf: 'عطف',
  faail: 'فاعل',
  fil: 'فعل',
  mafoolBiHi: 'مفعول به',
  mafoolFiyHi: 'مفعول فيه',
  mafoolLaHu: 'مفعول له',
  mafoolMutlaq: 'مفعول مطلق',
  majroor: 'مجرور',
  matoof: 'معطوف',
  matoofAlayh: 'معطوف عليه',
  mubtada: 'مبتدأ',
  mudaaf: 'مضاف',
  mudaafIlayhi: 'مضاف إليه',
  mutaalliq: 'متعلّق',
};
