export const TarkeebPlaces = {
  badal: 'بدل',
  haal: 'حال',
  harfMushabbahahBilFil: 'حرف مشبهة بالفعل',
  ismFilNaaqis: 'اسم فعل ناقص',
  ismHmbf: 'اسم حمبف',
  ismIshaarah: 'اسم الإشارة',
  jaar: 'جارّ',
  khabr: 'خبر',
  khabrFilNaaqis: 'خبر فعل ناقص',
  khabrHmbf: 'خبر حمبف',
  dhulHaal: 'ذو الحال',
  atf: 'عطف',
  faail: 'فاعل',
  fil: 'فعل',
  filNaaqis: 'فعل ناقص',
  mafoolBiHi: 'مفعول به',
  mafoolFiyHi: 'مفعول فيه',
  mafoolLaHu: 'مفعول له',
  mafoolMutlaq: 'مفعول مطلق',
  mafoolMaeahu: 'مفعول معه',
  majroor: 'مجرور',
  matoof: 'معطوف',
  matoofAlayh: 'معطوف عليه',
  mawsoof: 'موصوف',
  mubdalMinhu: 'مبدل منه',
  mubtada: 'مبتدأ',
  mudaaf: 'مضاف',
  mudaafIlayhi: 'مضاف إليه',
  mushaarunIlayh: 'مشار إليه',
  mutaalliq: 'متعلّق',
  shibhulFil: 'شبه الفعل',
  sifah: 'صفة',
};
