// Alphabet/Letters

export enum ArabicLetters {
  alif = 'ا',
  baa = 'ب',
  taa = 'ت',
  thaa = 'ث',
  jeem = 'ج',
  Haa = 'ح',
  khaa = 'خ',
  dhaal = 'د',
  zhaal = 'ذ',
  raa = 'ر',
  zaa = 'ز',
  seen = 'س',
  sheen = 'ش',
  saad = 'ص',
  daad = 'ض',
  Tha = 'ط',
  Zha = 'ظ',
  ein = 'ع',
  ghayn = 'غ',
  faa = 'ف',
  qaaf = 'ق',
  kaaf = 'ك',
  laam = 'ل',
  meem = 'م',
  nuun = 'ن',
  waw = 'و',
  haa = 'ه',
  hamza = 'أ',
  hamzaKasrah = 'إ',
  hamzaSmall = 'ء',
  yaa = 'ي',
}

export enum ArabicVowels {
  dammah = 'ُ',
  dammatain = 'ٌ',
  fathah = 'َ',
  fathatain = 'ً',
  harfIllahAlif = 'َا',
  harfIllahWaw = 'ُوْ',
  harfIllahYaa = 'ِيْ',
  kasrah = 'ِ',
  kasratain = 'ٍ',
}
